#!/usr/bin/env bash
# This script manages manage_my_process
DIR="$(cd "$(dirname "$0")" && pwd)"
case "$1" in
    start)
        "$DIR/manage_my_process" &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        "$DIR/manage_my_process" &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
